project:
  type: website

website:
  title: "blog"
  # navbar:
  #   left:
  #     - href: index.qmd
  #       text: Home
  #     - about.qmd
  sidebar: 
    style: "docked"
    search: true
    contents:
      - section: "FastAI Lesson Solutions"
        contents: 
          - posts/fastai_lessons/Lesson_2_Solutions.ipynb
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



